#!/bin/bash

backup() {
    echo "[INFO] Copying directories and files to their destination..."

    rsync -av "$origin" "$destination"

    echo
}

checkDependencies() {
    dependencies=("docker" "rsync")

    for dep in "${dependencies[@]}"; do
        if [ ! "$(command -v "$dep")" ]; then
            fatal "[ERROR] Command $dep not installed."
        fi
    done

    if [ $EUID != 0 ]; then
        fatal "[ERROR] Sudo privileges required."
    fi
}

fatal() {
    echo "$@" >&2
    kill -10 $proc
}

notify() {
    curl \
        -H "Title: $1" \
        -d "$2" \
        "http://ntfy.io/chronos"

    echo
}

startContainers() {
    echo "[INFO] Starting containers..."

    for container in $containers; do
        docker start "$container"
    done

    echo 
}

stopContainers() {
    echo "[INFO] Stopping containers..."

    for container in $containers; do
        docker stop "$container"
    done

    echo 
}

usage() {
    cat <<-EOF
	Usage: docker-backup -o /path/to/origin -d /path/to/destination
        -o  Origin directory where your Docker bind mounts are located
        -d  Backup destination path. Remote paths are also valid (i.e. username@192.168.1.100:/path/to/destination)
        -h  Show this help message and exit
	EOF
}

proc=$$
trap 'exit 1' SIGUSR1

checkDependencies

hostname=$(hostname)
containers=$(docker ps --format "{{.Names}}")

while getopts 'd:o:h' arg; do
		case $arg in
			d)
                destination=$OPTARG
            ;;
            o)
                origin=$(sed 's![^/]$!&/!' <<< "$OPTARG")
            ;;
            h)
            usage
            exit 2
            ;;
            *)
            usage
            exit 2
            ;;
    esac
done

if [ -z "$origin" ]; then
    fatal "[ERROR] Origin path not provided."
elif [ -z "$destination" ]; then
    fatal "[ERROR] Destination path not provided."
fi

hostname=$(hostname)
containers=$(docker ps --format "{{.Names}}")

if stopContainers; then
    if backup; then
        if startContainers; then
            notify "${hostname^}" "$origin: Backup completed." 
        else
            fatal "[ERROR] Unable to start containers."
        fi
    else
        notify "${hostname^}" "$origin: Backup failed." 
    fi
else
    fatal "[ERROR] Unable to stop containers."
fi
